// Bundle UMD libs (qrcode.js, pako.min.js) + src/app.js -> src/index.js
// UMD wrappers detect no module/exports in workerd and attach self.qrcode / self.pako
import { readFileSync, writeFileSync } from "node:fs";

const qr = readFileSync(new URL("../qrcode.js", import.meta.url), "utf8");
const pako = readFileSync(new URL("../pako.min.js", import.meta.url), "utf8");
const app = readFileSync(new URL("./app.js", import.meta.url), "utf8");

const out = [
  "// AUTO-GENERATED by build.js — edit src/app.js instead.",
  "// --- qrcode.js (MIT, Kazuhiko Arase) ---",
  qr,
  ";",
  "// --- pako 2.1.0 (MIT AND Zlib) ---",
  pako,
  ";",
  "// --- app ---",
  app,
].join("\n");

writeFileSync(new URL("./index.js", import.meta.url), out);
console.log("built src/index.js", out.length, "bytes");
